spring:
  # 数据库配置
  datasource:
    url: jdbc:p6spy:mysql://127.0.0.1:3306/cabinet?useSSL=true&useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF%2D8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: none
